const fs=require('fs'),path=require('path'),crypto=require('crypto');
const DB=path.join(process.cwd(),'data','db.json');const sessions=new Map();
function read(){return JSON.parse(fs.readFileSync(DB,'utf8'))}function write(db){try{fs.writeFileSync(DB,JSON.stringify(db,null,2))}catch(e){}}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data))}
function cookies(req){const o={};(req.headers.cookie||'').split(';').forEach(p=>{const [k,...v]=p.trim().split('=');if(k)o[k]=decodeURIComponent(v.join('='))});return o}
function auth(req){const sid=cookies(req).sid;return sid?sessions.get(sid):null}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
function id(p){return p+'_'+crypto.randomBytes(5).toString('hex')}function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g,'-').replace(/^-|-$/g,'')+'-'+crypto.randomBytes(3).toString('hex')}
function requireAuth(req,res){const a=auth(req);if(!a){json(res,401,{error:'未登录'});return null}return a}
module.exports=async(req,res)=>{try{const url=req.url.split('?')[0];
if(req.method==='POST'&&url==='/api/login'){const b=await body(req),db=read(),u=db.users.find(x=>x.email===b.email&&x.password===b.password);if(!u)return json(res,401,{error:'账号或密码错误'});const sid=crypto.randomBytes(24).toString('hex');sessions.set(sid,{user:{id:u.id,email:u.email,name:u.name,role:u.role},tenantId:u.tenantId});res.setHeader('Set-Cookie',`sid=${sid}; HttpOnly; Path=/; SameSite=Lax`);return json(res,200,{ok:true})}
if(req.method==='POST'&&url==='/api/logout'){const sid=cookies(req).sid;if(sid)sessions.delete(sid);res.setHeader('Set-Cookie','sid=; Max-Age=0; Path=/');return json(res,200,{ok:true})}
if(url.startsWith('/api/')){const a=requireAuth(req,res);if(!a)return;const db=read(),t=a.tenantId;if(req.method==='GET'){if(url==='/api/me')return json(res,200,{user:a.user,tenant:db.tenants.find(x=>x.id===t)});const map={plugins:'plugins',automations:'automations',groups:'groups',shortcuts:'shortcuts','customer-accounts':'customerAccounts'};for(const [r,k] of Object.entries(map))if(url===`/api/${r}`)return json(res,200,db[k].filter(x=>x.tenantId===t));if(url==='/api/dashboard')return json(res,200,{plugins:db.plugins.filter(x=>x.tenantId===t).length,automations:db.automations.filter(x=>x.tenantId===t).length,groups:db.groups.filter(x=>x.tenantId===t).length,shortcuts:db.shortcuts.filter(x=>x.tenantId===t).length,customerAccounts:(db.customerAccounts||[]).filter(x=>x.tenantId===t).length})}
if(req.method==='POST'){const b=await body(req);if(url==='/api/plugins'){const x={id:id('plugin'),tenantId:t,name:b.name,status:'active',automationId:b.automationId||null,groupId:b.groupId||null};db.plugins.push(x);write(db);return json(res,201,x)}if(url==='/api/automations'){const x={id:id('auto'),tenantId:t,name:b.name,description:b.description||'',status:'active'};db.automations.push(x);write(db);return json(res,201,x)}if(url==='/api/groups'){const x={id:id('group'),tenantId:t,name:b.name,status:'active',members:[]};db.groups.push(x);write(db);return json(res,201,x)}if(url==='/api/customer-accounts'){if(!['owner','主管'].includes(a.user.role))return json(res,403,{error:'只有总管理员或主管可以创建客服账号'});if(!b.teamId)return json(res,400,{error:'必须选择所属团队'});const g=(db.groups||[]).find(x=>x.id===b.teamId&&x.tenantId===t);if(!g)return json(res,400,{error:'所属团队不存在'});db.customerAccounts=db.customerAccounts||[];if(db.customerAccounts.some(x=>x.email===b.email))return json(res,400,{error:'该邮箱已经存在'});const x={id:id('agent'),tenantId:t,teamId:b.teamId,name:b.name,email:b.email,password:b.password,role:(['主管','客服'].includes(b.role)?b.role:'客服'),status:'active',createdAt:new Date().toISOString()};db.customerAccounts.push(x);g.members=g.members||[];g.members.push(x.id);write(db);const safe={...x};delete safe.password;return json(res,201,safe)}if(url==='/api/shortcuts'){const x={id:id('shortcut'),tenantId:t,pluginId:b.pluginId,name:b.name,type:'automation',automationId:b.automationId,slug:slug(b.name),active:true};db.shortcuts.push(x);write(db);return json(res,201,{...x,url:`/go/${x.slug}`})}}
return json(res,404,{error:'Not found'})}
if(req.method==='GET'&&url.startsWith('/go/')){const db=read(),s=db.shortcuts.find(x=>x.slug===url.slice(4));if(!s)return json(res,404,{error:'入口不存在'});const p=db.plugins.find(x=>x.id===s.pluginId),a=db.automations.find(x=>x.id===s.automationId),g=db.groups.find(x=>x.id===p?.groupId);res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:system-ui;background:#f5f7fb;display:grid;place-items:center;min-height:100vh;margin:0}.box{background:white;border:1px solid #e7ebf2;border-radius:18px;padding:32px;max-width:560px;box-shadow:0 20px 60px #0001}.tag{display:inline-block;padding:6px 10px;background:#eff6ff;color:#1d4ed8;border-radius:999px}</style><div class="box"><span class="tag">${p?.name||''}</span><h1>${s.name}</h1><p>进入 AI 自动化：<b>${a?.name||'待配置'}</b></p><p>下一步客服分配：<b>${g?.name||'待配置'}</b></p><p>这是快捷入口路由验证页，后续将替换为真实聊天窗口。</p></div>`)}
return json(res,404,{error:'Not found'})}catch(e){console.error(e);return json(res,500,{error:'服务器错误',detail:e.message})}}
